"""
Unit tests for demo_plugin plugin
"""

import pytest
from unittest.mock import Mock, AsyncMock, MagicMock
from ..plugin import DemoPluginPlugin


@pytest.fixture
def mock_plugin_manager():
    """Create a mock plugin manager"""
    manager = Mock()
    manager.get_interface = Mock(return_value=Mock())
    manager.message_router = Mock()
    manager.database = Mock()
    return manager


@pytest.fixture
def plugin(mock_plugin_manager):
    """Create a plugin instance for testing"""
    config = {
        "enabled": True,
        
        "task_interval": 60,
        
    }
    return DemoPluginPlugin("demo_plugin", config, mock_plugin_manager)


@pytest.mark.asyncio
async def test_plugin_initialization(plugin):
    """Test plugin initialization"""
    result = await plugin.initialize()
    assert result is True


@pytest.mark.asyncio
async def test_plugin_disabled(mock_plugin_manager):
    """Test plugin with disabled configuration"""
    config = {"enabled": False}
    plugin = DemoPluginPlugin("demo_plugin", config, mock_plugin_manager)
    
    result = await plugin.initialize()
    assert result is False



@pytest.mark.asyncio
async def test_example_command(plugin):
    """Test example command handler"""
    await plugin.initialize()
    
    args = ["test", "args"]
    context = {
        "sender_id": "test_user",
        "channel": "test_channel"
    }
    
    response = await plugin.handle_example_command(args, context)
    assert response is not None
    assert "test_user" in response or "Hello" in response



def test_plugin_metadata(plugin):
    """Test plugin metadata"""
    metadata = plugin.get_metadata()
    
    assert metadata.name == "demo_plugin"
    assert metadata.version == "1.0.0"
    assert metadata.description == "Demo plugin generated by template"
    assert metadata.author == "ZephyrGate Team"


@pytest.mark.asyncio
async def test_plugin_shutdown(plugin):
    """Test plugin shutdown"""
    await plugin.initialize()
    await plugin.shutdown()
    # Verify cleanup was performed



@pytest.mark.asyncio
async def test_periodic_task(plugin):
    """Test periodic task handler"""
    await plugin.initialize()
    
    # Execute the periodic task
    await plugin.periodic_task_handler()
    
    # Verify task executed successfully
    # Add specific assertions based on your task logic




