"""
demo_plugin Plugin

Demo plugin generated by template

Author: ZephyrGate Team
Version: 1.0.0
"""

from typing import Dict, Any, List
from src.core.enhanced_plugin import EnhancedPlugin
from src.core.plugin_manager import PluginMetadata, PluginPriority


class DemoPluginPlugin(EnhancedPlugin):
    """
    Demo plugin generated by template
    """
    
    async def initialize(self) -> bool:
        """
        Initialize the plugin.
        
        This method is called when the plugin is loaded. Register commands,
        message handlers, scheduled tasks, and menu items here.
        
        Returns:
            True if initialization successful, False otherwise
        """
        self.logger.info("Initializing demo_plugin plugin")
        
        # Get configuration
        self.enabled = self.get_config("enabled", True)
        
        if not self.enabled:
            self.logger.info("Plugin is disabled in configuration")
            return False
        
        
        # Register commands
        self.register_command(
            command="example",
            handler=self.handle_example_command,
            help_text="Example command - replace with your own",
            priority=100
        )
        
        
        
        # Register scheduled tasks
        task_interval = self.get_config("task_interval", 300)  # Default: 5 minutes
        self.register_scheduled_task(
            name="periodic_task",
            handler=self.periodic_task_handler,
            interval=task_interval
        )
        
        
        
        
        self.logger.info("demo_plugin plugin initialized successfully")
        return True
    
    
    async def handle_example_command(self, args: List[str], context: Dict[str, Any]) -> str:
        """
        Handle the example command.
        
        Args:
            args: Command arguments
            context: Command context (sender, channel, etc.)
            
        Returns:
            Response message
        """
        sender = context.get('sender_id', 'unknown')
        
        
        
        response = f"Hello {sender}! This is an example command."
        
        
        return response
    
    
    
    async def periodic_task_handler(self):
        """
        Handler for periodic scheduled task.
        
        This task runs at the interval specified in configuration.
        """
        self.logger.info("Periodic task executing")
        
        
        
        # Add your periodic task logic here
        self.logger.info("Periodic task completed")
    
    
    
    
    async def shutdown(self) -> None:
        """
        Shutdown the plugin.
        
        This method is called when the plugin is being stopped.
        Clean up resources here.
        """
        self.logger.info("Shutting down demo_plugin plugin")
        
        # Add cleanup logic here
        
        await super().shutdown()
    
    def get_metadata(self) -> PluginMetadata:
        """
        Get plugin metadata.
        
        Returns:
            Plugin metadata
        """
        return PluginMetadata(
            name="demo_plugin",
            version="1.0.0",
            description="Demo plugin generated by template",
            author="ZephyrGate Team",
            priority=PluginPriority.NORMAL,
            enabled=self.get_config("enabled", True)
        )


# Plugin factory function (optional)
def create_plugin(name: str, config: dict, plugin_manager):
    """
    Create and return plugin instance.
    
    Args:
        name: Plugin name
        config: Plugin configuration
        plugin_manager: Plugin manager instance
        
    Returns:
        Plugin instance
    """
    return DemoPluginPlugin(name, config, plugin_manager)
